ALTER TABLE satellites
ADD COLUMN IF NOT EXISTS internal_temperature DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS external_temperature DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS battery_voltage DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS last_telemetry_time TIMESTAMP;